#!/usr/bin/env php
<?php

use Arrilot\BitrixMigrations\Commands\MakeCommand;
use Arrilot\BitrixMigrations\Commands\InstallCommand;
use Arrilot\BitrixMigrations\Commands\MigrateCommand;
use Arrilot\BitrixMigrations\Commands\RollbackCommand;
use Arrilot\BitrixMigrations\Repositories\BitrixDatabaseRepository;
use Symfony\Component\Console\Application;

$_SERVER["DOCUMENT_ROOT"] = __DIR__;
include $_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php";

$config = [
    'table' => 'migrations',
    'dir' => $_SERVER['DOCUMENT_ROOT'].'/migrations'
];

$database = new BitrixDatabaseRepository($config['table']);

$app = new Application('Bitrix migrations');

$app->add(new InstallCommand($config, $database));
$app->add(new MakeCommand($config));
$app->add(new MigrateCommand($config, $database));
$app->add(new RollbackCommand($config, $database));

$app->run();
